version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - apt-get update
  pre_build:
    commands:
      - echo START
      - ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - ECR_FOLDER=dotpen-api
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
      - IMAGE_TAG=${TIMESTAMP:=latest}
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_FOLDER
      - corepack enable pnpm
      - pnpm install
  build:
    commands:
      - pnpm test
      - pnpm lint
      - pnpm build
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing to repo
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - echo END
artifacts:
  files:
    - '**/*'
  base-directory: './dist/'