version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - apt-get update
  pre_build:
    commands:
      - echo START
      - corepack enable pnpm
      - pnpm install
  build:
    commands:
      - pnpm test
      - pnpm lint
      - pnpm build
  post_build:
    commands:
      - echo END

artifacts:
  files:
    - '**/*'
  base-directory: './dist/'