version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - apt-get update
  pre_build:
    commands:
      - echo START
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_FOLDER
      - corepack enable pnpm
      - pnpm install
  build:
    commands:
      - pnpm test
      - pnpm lint
      - pnpm build
      - echo $REPOSITORY_URI
  post_build:
    commands:
      - echo END
artifacts:
  files:
    - '**/*'
  base-directory: './dist/'