version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install curl
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
  pre_build:
    commands:
      - echo START
      - nvm use
      - corepack enable pnpm
      - pnpm install
  build:
    commands:
      - pnpm test
      - pnpm lint
      - pnpm build
  post_build:
    commands:
      - echo END

artifacts:
  files:
    - '**/*'
  base-directory: './dist/'