export enum CharacterRelationType {
  FRIENDSHIP = "FRIENDSHIP",
  ANIMOSITY = "ANIMOSITY",
  KILLED = "KILLED",
  KINSHIIP = "KINSHIIP",
  PEDAGOGY = "PEDAGOGY",
  VASSALAGE = "VASSALAGE",
  WORSHIP = "WORSHIP",
}
